#ifndef GUARD_MINING_CONSTANTS

#define GUARD_MINING_CONSTANTS


/*********** OTHER ************/
#define MINING_ITEM_TILE_NONE           0
#define MINING_ITEM_TILE_DUG_UP         5
#define MINING_MAX_NUM_BURIED_ITEMS     4
#define MINING_MAX_NUM_BURIED_STONES    2

/*********** SOUNDS ************/
#define MINING_SE_HIT_HAMMER            SE_M_ROCK_THROW
#define MINING_SE_HIT_PICKAXE           SE_M_DIG
#define MINING_SE_HIT_DUG_UP            SE_ICE_STAIRS
#define MINING_SE_WALL_COLLAPSE         SE_M_EARTHQUAKE
#define MINING_SE_TOOL_SWITCH           SE_ROTATING_GATE
#define MINING_SE_ITEM_SPARKLE          SE_RG_CARD_OPEN

/*********** ITEM SPRITE TAGS ************/
enum
{
    MINING_TAG_ITEM_HEARTSCALE = 12,
    MINING_TAG_ITEM_HARDSTONE,
    MINING_TAG_ITEM_REVIVE,
    MINING_TAG_ITEM_STAR_PIECE,
    MINING_TAG_ITEM_DAMP_ROCK,
    MINING_TAG_ITEM_RED_SHARD,
    MINING_TAG_ITEM_BLUE_SHARD,
    MINING_TAG_ITEM_IRON_BALL,
    MINING_TAG_ITEM_REVIVE_MAX,
    MINING_TAG_ITEM_EVER_STONE,
    MINING_TAG_ITEM_OVAL_STONE,
    MINING_TAG_ITEM_LIGHT_CLAY,
    MINING_TAG_ITEM_HEAT_ROCK,
    MINING_TAG_ITEM_ICY_ROCK,
    MINING_TAG_ITEM_SMOOTH_ROCK,
    MINING_TAG_ITEM_YELLOW_SHARD,
    MINING_TAG_ITEM_GREEN_SHARD,
    MINING_TAG_ITEM_LEAF_STONE,
    MINING_TAG_ITEM_FIRE_STONE,
    MINING_TAG_ITEM_WATER_STONE,
    MINING_TAG_ITEM_THUNDER_STONE,
    MINING_TAG_ITEM_MOON_STONE,
    MINING_TAG_ITEM_SUN_STONE,
    MINING_TAG_ITEM_ODD_KEY_STONE,
    MINING_TAG_ITEM_SKULL_FOSSIL,
    MINING_TAG_ITEM_ARMOR_FOSSIL,
    MINING_TAG_ITEM_HELIX_FOSSIL,
    MINING_TAG_ITEM_DOME_FOSSIL,
    MINING_TAG_ITEM_OLD_AMBER,
    MINING_TAG_ITEM_CLAW_FOSSIL,
    MINING_TAG_ITEM_ROOT_FOSSIL,
    MINING_TAG_ITEM_COVER_FOSSIL,
    MINING_TAG_ITEM_PLUME_FOSSIL,
    MINING_TAG_ITEM_JAW_FOSSIL,
    MINING_TAG_ITEM_SAIL_FOSSIL,
    MINING_TAG_ITEM_FOSSILIZED_BIRD,
    MINING_TAG_ITEM_FOSSILIZED_DINO,
    MINING_TAG_ITEM_FOSSILIZED_DRAKE,
    MINING_TAG_ITEM_FOSSILIZED_FISH,
    MINING_TAG_ITEM_RARE_BONE,

    MINING_TAG_STONE_1X4,
    MINING_TAG_STONE_4X1,
    MINING_TAG_STONE_2X4,
    MINING_TAG_STONE_4X2,
    MINING_TAG_STONE_2X2,
    MINING_TAG_STONE_3X3,
    MINING_TAG_STONE_SNAKE1,
    MINING_TAG_STONE_SNAKE2,
    MINING_TAG_STONE_MUSHROOM1,
    MINING_TAG_STONE_MUSHROOM2,
};

/*********** FLAGS ************/
#define MINING_FLAG_USE_DEFAULT_MESSAGE_BOX            FALSE

enum
{
    MININGID_NONE,
    MININGID_STONE_1x4,
    MININGID_STONE_4x1,
    MININGID_STONE_2x4,
    MININGID_STONE_4x2,
    MININGID_STONE_2x2,
    MININGID_STONE_3x3,
    MININGID_STONE_SNAKE1,
    MININGID_STONE_SNAKE2,
    MININGID_STONE_MUSHROOM1,
    MININGID_STONE_MUSHROOM2,
    MININGID_HEART_SCALE,
    MININGID_HARD_STONE,
    MININGID_REVIVE,
    MININGID_STAR_PIECE,
    MININGID_DAMP_ROCK,
    MININGID_RED_SHARD,
    MININGID_BLUE_SHARD,
    MININGID_IRON_BALL,
    MININGID_REVIVE_MAX,
    MININGID_EVER_STONE,
    MININGID_OVAL_STONE,
    MININGID_LIGHT_CLAY,
    MININGID_HEAT_ROCK,
    MININGID_ICY_ROCK,
    MININGID_SMOOTH_ROCK,
    MININGID_YELLOW_SHARD,
    MININGID_GREEN_SHARD,
    MININGID_LEAF_STONE,
    MININGID_FIRE_STONE,
    MININGID_WATER_STONE,
    MININGID_THUNDER_STONE,
    MININGID_MOON_STONE,
    MININGID_SUN_STONE,
    MININGID_ODD_KEY_STONE,
    MININGID_SKULL_FOSSIL,
    MININGID_ARMOR_FOSSIL,
    MININGID_HELIX_FOSSIL,
    MININGID_DOME_FOSSIL,
    MININGID_OLD_AMBER,
    MININGID_CLAW_FOSSIL,
    MININGID_ROOT_FOSSIL,
    MININGID_COVER_FOSSIL,
    MININGID_PLUME_FOSSIL,
    MININGID_JAW_FOSSIL,
    MININGID_SAIL_FOSSIL,
    MININGID_FOSSILIZED_BIRD,
    MININGID_FOSSILIZED_DINO,
    MININGID_FOSSILIZED_DRAKE,
    MININGID_FOSSILIZED_FISH,
    MININGID_RARE_BONE,
};

#define MINING_COUNT_ID_STONE           MININGID_STONE_MUSHROOM2

#define MINING_ZONE_WIDTH 12
#define MINING_ZONE_HEIGHT 8

#define MINING_ZONE_1_X_LEFT_BOUNDARY     0
#define MINING_ZONE_1_X_RIGHT_BOUNDARY    5
#define MINING_ZONE_1_Y_UP_BOUNDARY       0
#define MINING_ZONE_1_Y_DOWN_BOUNDARY     3

#define MINING_ZONE_2_X_LEFT_BOUNDARY     0
#define MINING_ZONE_2_X_RIGHT_BOUNDARY    5
#define MINING_ZONE_2_Y_UP_BOUNDARY       4
#define MINING_ZONE_2_Y_DOWN_BOUNDARY     MINING_ZONE_HEIGHT - 1;

#define MINING_ZONE_3_X_LEFT_BOUNDARY     6
#define MINING_ZONE_3_X_RIGHT_BOUNDARY    MINING_ZONE_WIDTH - 1
#define MINING_ZONE_3_Y_UP_BOUNDARY       0
#define MINING_ZONE_3_Y_DOWN_BOUNDARY     3

#define MINING_ZONE_4_X_LEFT_BOUNDARY     6
#define MINING_ZONE_4_X_RIGHT_BOUNDARY    MINING_ZONE_WIDTH - 1
#define MINING_ZONE_4_Y_UP_BOUNDARY       4
#define MINING_ZONE_4_Y_DOWN_BOUNDARY     MINING_ZONE_HEIGHT - 1

/*********** DEBUG FLAGS ************/
#define MINING_DEBUG_ENABLE                                 FALSE

#if MINING_DEBUG_ENABLE == TRUE
    #define MINING_DEBUG_ALL_SPRITES_VISIBLE                TRUE
    #define MINING_DEBUG_INFINITE_HITS                      FALSE
    #define MINING_DEBUG_ENABLE_ITEM_GENERATION_OPTIONS     TRUE
    #define MINING_DEBUG_ENABLE_STONE_GENERATION_OPTIONS    FALSE

    #if MINING_DEBUG_ENABLE_ITEM_GENERATION_OPTIONS == TRUE
        #define MINING_DEBUG_DESIRED_NUMBER_OF_ITEMS   2
        #define MINING_DEBUG_MININGID_ITEM1            MININGID_LEAF_STONE
        #define MINING_DEBUG_MININGID_ITEM2            MININGID_THUNDER_STONE
        #define MINING_DEBUG_MININGID_ITEM3            MININGID_THUNDER_STONE
        #define MINING_DEBUG_MININGID_ITEM4            MININGID_SUN_STONE
    #endif

    #if MINING_DEBUG_ENABLE_STONE_GENERATION_OPTIONS == TRUE
        #define MINING_DEBUG_MININGID_STONE1           MININGID_STONE_MUSHROOM1
        #define MINING_DEBUG_MININGID_STONE2           MININGID_STONE_MUSHROOM2
    #endif
#endif

#endif
