// DO NOT MODIFY THIS FILE'S CONTENT! THE CONTENT OF THIS FILE IS AUTOGENERATED! ONLY MODIFY THIS FILE IF YOU KNOW WHAT YOU ARE DOING!
#include "constants/mining_minigame.h"

static const int SpriteTileTable[][16] = {
    [ITEMID_WATER_STONE] = {
      1,1,1,0,1,1,1,0,1,1,0,0,0,0,0,0,
    },
    [ITEMID_ARMOR_FOSSIL] = {
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    },
    [ITEMID_MOON_STONE] = {
      0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,
    },
    [ITEMID_STAR_PIECE] = {
      0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,
    },
    [ITEMID_LEAF_STONE] = {
      0,1,0,0,1,1,1,0,1,1,1,0,0,1,0,0,
    },
    [ITEMID_ICY_ROCK] = {
      0,1,1,0,1,1,1,1,1,1,1,1,1,0,0,1,
    },
    [ITEMID_HARD_STONE] = {
      1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,
    },
    [ITEMID_DAMP_ROCK] = {
      1,1,1,0,1,1,1,0,1,0,1,0,0,0,0,0,
    },
    [ITEMID_ODD_KEY_STONE] = {
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    },
    [ITEMID_SKULL_FOSSIL] = {
      1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,
    },
    [ITEMID_FIRE_STONE] = {
      1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_GREEN_SHARD] = {
      1,1,1,1,1,1,1,1,1,1,0,1,0,0,0,0,
    },
    [ITEMID_HEART_SCALE] = {
      1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,
    },
    [ITEMID_THUNDER_STONE] = {
      0,1,1,0,1,1,1,0,1,1,0,0,0,0,0,0,
    },
    [ITEMID_REVIVE_MAX] = {
      1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_HEAT_ROCK] = {
      1,0,1,0,1,1,1,1,1,1,1,1,0,0,0,0,
    },
    [ITEMID_YELLOW_SHARD] = {
      1,0,1,0,1,1,1,0,1,1,1,1,0,0,0,0,
    },
    [ITEMID_OVAL_STONE] = {
      1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_EVER_STONE] = {
      1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,
    },
    [ITEMID_IRON_BALL] = {
      1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_SMOOTH_ROCK] = {
      0,0,1,0,1,1,1,0,0,1,1,1,0,1,0,0,
    },
    [ITEMID_BLUE_SHARD] = {
      1,1,1,0,1,1,1,0,1,1,0,0,0,0,0,0,
    },
    [ITEMID_RED_SHARD] = {
      1,1,1,0,1,1,0,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_REVIVE] = {
      0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,
    },
    [ITEMID_LIGHT_CLAY] = {
      1,0,1,0,1,1,1,0,1,1,1,1,0,1,0,1,
    },
    [ITEMID_SUN_STONE] = {
      0,1,0,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ID_STONE_MUSHROOM2] = {
      0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_2x4] = {
      1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,
    },
    [ID_STONE_1x4] = {
      1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,
    },
    [ID_STONE_SNAKE1] = {
      1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_2x2] = {
      1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_4x2] = {
      1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_4x1] = {
      1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_3x3] = {
      1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ID_STONE_SNAKE2] = {
      0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_MUSHROOM1] = {
      1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,
    },
};